services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./CMakeLists.txt
        target: /app/CMakeLists.txt
      - type: bind
        source: ./Jour1
        target: /app/Jour1
      - type: bind
        source: ./build
        target: /app/build
    command: bash
    tty: true
    stdin_open: true
